name: DEV CI Pipeline for Web

on:
  push:
    branches:
      - '*'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn run lint

      - name: Build
        run: yarn run build

  deploy-test:
    needs: lint_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
            make build-image
      
      - name: Test 
        run: |
            make test
      
      - name: Push Docker image
        run: |
            echo "push-image"

      - name: Deploy to Test
        run: |
          echo "TODO: DEPLOY TO TEST"
  deploy-qa:
    needs: lint_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
            make build-image
      
      - name: Test 
        run: |
            make test
      
      - name: Push Docker image
        run: |
            echo "push-image"

      - name: Deploy to QA
        run: |
          echo "TODO: DEPLOY TO QA"
