name: DEV CI Pipeline for Web

on:
  push:
    branches:
      - "develop" # matches every branch

jobs:
  lint_and_build:
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: "http://47.128.81.230:8004"
      TARGET: "/home/ec2-user/.deploy/RainScales/mge_be/deployment/"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn run lint

      - name: Build
        run: |
          echo "export VITE_API_URL=${{ env.VITE_API_URL }} > .env"
          yarn run build

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          key: ${{ secrets.EC2_SECRET }}
          source: "dist"
          target: ${{env.TARGET}}/
