name: CI/CD Pipeline for Web

on:
  push:
    branches:
      - '*'

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn run lint

      - name: Build
        run: yarn run build
  push-image:
    name: Push Docker image to Docker Hub
    needs: lint_and_build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
            make build-image
            make push-image
  deploy-test:
    needs: lint_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy to DEV
        run: |
          echo "TODO: DEPLOY TO DEV"
  deploy-qa:
    needs: lint_and_build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to QA
        run: |
          echo "TODO: DEPLOY TO QA"
  
